-- NVL로 설정하게 되면 해당 필드를 수정할 수 없도록 만들게 됩니다. 
CREATE VIEW V_EMP1(EMP_ID,FIRST_NAME,JOB_ID,HIRE_dATE,DEPT_ID) AS 
SELECT EMPLOYEE_ID, NVL(FIRST_NAME,NULL), JOB_ID, HIRE_DATE, DEPARTMENT_ID    -- 논리적인 집합 
FROM EMPLOYEES 
WHERE JOB_ID = 'SH_CLERK';
-- V_EMP1의 FIRST_NAME 은 수정 할 수 없는 형태로 만들어 두었기때문에 ' 가상 열 사용 불가 ' 메시지가 출력됩니다. 
UPDATE V_EMP1 SET FIRST_NAME ='KYLE' WHERE FIRST_NAME = 'Julia'; 



CREATE VIEW V_EMP_SALARY(EMP_ID, LAST_NAME, ANNUAL_SAL) AS 
SELECT EMPLOYEE_ID, LAST_NAME, (SALARY+NVL(COMMISSION_PCT,0))*12 
FROM EMPLOYEES; 

SELECT * FROM V_EMP_SALARY;


CREATE VIEW V_CUSTOM AS 
SELECT EMPLOYEE_ID, LAST_NAME , DEPARTMENT_ID ,HIRE_DATE  
FROM EMPLOYEES 
WHERE (SALARY+NVL(COMMISSION_PCT,0))*12 > 30000 
AND DEPARTMENT_ID = 50 
AND JOB_ID = 'ST_CLERK' 
AND SYSDATE - 365*5 > HIRE_DATE; 

SELECT * FROM V_CUSTOM; 


CREATE VIEW 사원 (사번, 이름, 부서번호, 입사일 ) AS 
SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME , DEPARTMENT_ID, HIRE_DATE 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 50; 

SELECT * FROM 사원; 

CREATE VIEW V_JOIN(사번, 이름, 부서번호, 부서명, 입사일) AS 
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME||' '||EMP.LAST_NAME , EMP.DEPARTMENT_ID,  
        DEPT.DEPARTMENT_NAME, EMP.HIRE_DATE 
FROM EMPLOYEES EMP, DEPARTMENTS DEPT 
WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID; 

SELECT * FROM V_JOIN; 
